### ISSUE TITLE
many problems.

### ISSUE THREAD

**Issue by mid787** [Tynarus/angular-seed#22]
1 - tsconfig is not in root - so it causes compilaton problems : 

https://i.imgur.com/8HPpusN.jpg

2- when running `npm run start` it does compile  : 

 https://i.imgur.com/tleMeB3.jpg

But at 3000 there is an error : 

https://i.imgur.com/4MJL3SU.jpg

here is the small demo  project : https://ufile.io/j184w

**Comment by TomasKatz** [comment]
There is a serious problem with generation of source maps to.
Source maps do not generate, and I went trough all of the possible configurations for **devTool**, also posted a detaild stackoverflow question about it [here](https://stackoverflow.com/questions/47331774/no-possible-value-in-the-devtool-property-of-webpack-common-js-will-generate-ma) .

Royi have a nice flight :)

**Comment by mid787** [comment]
Tnx
